// examples/angular/src/app/bal-components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { balClaimNumber } from '@baloise/ui-library-utils'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent implements OnInit {
  claimNumber: string = '93001217169'

  constructor() { }

  ngOnInit(): void {
  }

  claimNumberFormatted() {
    return balClaimNumber(this.claimNumber);
  }

}

<div class="container">
    <h1 class="title is-size-1">Filters</h1>
    <p>{{ '123' | balClaimNumber }}</p>
    <p>{{ '73001217169' | balClaimNumber }}</p>
    <p>{{ claimNumberFormatted() }}</p>
</div>

// examples/vue/src/views/Home.vue
<template>
  <div>
    <h1 class="title is-size-1">Filters</h1>
    <p>{{ '123' | balClaimNumber }}</p>
    <p>{{ '73001217169' | balClaimNumber }}</p>
    <p>{{ claimNumberFormatted }}</p>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { balClaimNumber } from '@baloise/ui-library'

export default Vue.extend({
  name: 'Home',
  data: () => {
    return {
      claimNumber: '93001217169',
    }
  },
  computed: {
    claimNumberFormatted: function () {
      return balClaimNumber(this.claimNumber)
    },
  },
})
</script>
