// examples/angular/src/app/modal/modal.component.ts
import { Component, ViewChild } from '@angular/core';
import type { Components } from '@baloise/ui-library';

@Component({
  selector: 'app-modal',
  templateUrl: './modal.component.html',
})
export class ModalComponent {
  @ViewChild('modal') modal!: Components.BalModal;

  constructor() {}

  ngOnInit(): void {}

  openModal() {
    this.modal.open();
  }

  closeModal() {
    this.modal.close();
  }
}

<h1 class="title is-size-1 has-no-margin-top">Modal</h1>

<bal-button (click)="openModal()">Open Modal</bal-button>

<bal-modal #modal>
  <bal-modal-header>Modal Title</bal-modal-header>
  <bal-modal-body>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat.
    </p>
  </bal-modal-body>
  <bal-modal-footer>
    <bal-modal-actions>
      <bal-button color="link" (click)="closeModal()">Cancel</bal-button>
      <bal-button color="primary" (click)="closeModal()">Okay</bal-button>
    </bal-modal-actions>
  </bal-modal-footer>
</bal-modal>

// examples/vue/src/views/Modal.vue
<template>
  <div>
    <h1 class="title is-size-1">Modal</h1>
    <BalButton @click="openModal()">Open Modal</BalButton>

    <BalModal ref="modal">
      <BalModalHeader>Modal Title</BalModalHeader>
      <BalModalBody>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.
        </p>
      </BalModalBody>
      <BalModalFooter>
        <BalModalActions>
          <BalButton type="link" @click="closeModal()">Cancel</BalButton>
          <BalButton type="primary" @click="closeModal()">Okay</BalButton>
        </BalModalActions>
      </BalModalFooter>
    </BalModal>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import {
  BalButton,
  BalModal,
  BalModalBody,
  BalModalFooter,
  BalModalHeader,
  BalModalActions,
} from '@baloise/ui-library-vue-2'

export default Vue.extend({
  methods: {
    openModal: function() {
      const modal = this.$refs.modal as HTMLBalModalElement
      modal.open()
    },
    closeModal: function() {
      const modal = this.$refs.modal as HTMLBalModalElement
      modal.close()
    },
  },
  components: {
    BalButton,
    BalModal,
    BalModalBody,
    BalModalFooter,
    BalModalHeader,
    BalModalActions,
  },
})
</script>
