// examples/angular/src/app/services/services.component.ts
import { Component } from '@angular/core'
import { BalSnackbarService, BalToastService } from '@baloise/design-system-components-angular'

@Component({
  selector: 'app-services',
  templateUrl: './services.component.html',
})
export class ServicesComponent {
  constructor(public toast: BalToastService, public snackbar: BalSnackbarService) {}

  createToast() {
    this.toast.create({ message: 'I am a nice Toast!' })
  }

  createSnackbar() {
    this.snackbar.create({
      icon: 'github',
      subject: 'Snackbar Title',
      message: 'I am the body of a nice snackbar',
    })
  }
}

<h1 class="title is-size-1 has-no-margin-top">Services</h1>

<h2 class="title is-size-2 has-no-margin-top">Toast</h2>
<bal-button (click)="createToast()">Create Toast</bal-button>

<h2 class="title is-size-2">Snackbar</h2>
<bal-button (click)="createSnackbar()">Create Snackbar</bal-button>

// examples/vue/src/app/pages/Services.vue
<template>
  <bal-card class="mt-6">
    <bal-card-content>
      <bal-heading space="bottom">Services</bal-heading>

      <bal-heading level="h2" space="top">Toast</bal-heading>
      <bal-button @click="createToast()">Create Toast</bal-button>

      <bal-heading level="h2" space="top">Snackbar</bal-heading>
      <bal-button @click="createSnackbar()">Create Snackbar</bal-button>
    </bal-card-content>
  </bal-card>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { balSnackbarController, balToastController } from '@baloise/design-system-components'

export default defineComponent({
  components: {},
  setup() {
    function createToast() {
      balToastController.create({ message: 'I am a nice Toast!' })
    }

    function createSnackbar() {
      balSnackbarController.create({
        icon: 'github',
        subject: 'Snackbar Title',
        message: 'I am the body of a nice snackbar',
      })
    }

    return {
      createToast,
      createSnackbar,
    }
  },
})
</script>
