// examples/vue/src/app/pages/Modal.vue
<template>
  <bal-card class="mt-6">
    <bal-card-content>
      <bal-heading space="bottom">Modal</bal-heading>

      <bal-button @click="openModal()">Open Modal</bal-button>
    </bal-card-content>
  </bal-card>

  <bal-modal ref="modalRef">
    <bal-modal-header>Modal Title</bal-modal-header>
    <bal-modal-body>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat.
      </p>
    </bal-modal-body>
    <bal-modal-footer>
      <bal-modal-actions>
        <bal-button color="link" @click="closeModal()">Cancel</bal-button>
        <bal-button color="primary" @click="closeModal()">Okay</bal-button>
      </bal-modal-actions>
    </bal-modal-footer>
  </bal-modal>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import { Components } from '@baloise/design-system-components'

export default defineComponent({
  components: {},
  setup() {
    const modalRef = ref<{ $el: Components.BalModal }>()

    function openModal() {
      modalRef.value?.$el.open()
    }

    function closeModal() {
      modalRef.value?.$el.close()
    }

    return {
      modalRef,
      openModal,
      closeModal,
    }
  },
})
</script>

// apps/angular/base/app/src/app/modal.component.ts
import { Component, Input } from '@angular/core'
import { CommonModule } from '@angular/common'
import { BalModalService, BaloiseDesignSystemModule } from '@baloise/design-system-components-angular'

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [CommonModule, BaloiseDesignSystemModule],
  template: `
    <bal-modal-header>Modal Title</bal-modal-header>
    <bal-modal-body>
      <p>{{ firstName }}</p>
      <p>{{ lastName }}</p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua.
      </p>
      <bal-button-group position="right" class="mt-medium">
        <bal-button color="link" (click)="closeModal()">Cancel</bal-button>
        <bal-button color="primary" (click)="closeModal()">Okay</bal-button>
      </bal-button-group>
    </bal-modal-body>
  `,
})
export class ModalComponent {
  @Input() firstName!: string
  @Input() lastName!: string

  constructor(private modalService: BalModalService) {}

  closeModal() {
    this.modalService.dismiss({
      firstName: this.firstName,
      lastName: this.lastName,
      dismissed: true,
    })
  }
}
