// packages/output-targets/angular/src/output-angular.ts
import path from 'path'
import type { CompilerCtx, ComponentCompilerMeta, Config } from '@stencil/core/internal'
import type { OutputTargetAngular, PackageJSON } from './types'
import {
  relativeImport,
  normalizePath,
  sortBy,
  readPackageJson,
  dashToPascalCase,
  createImportStatement,
} from './utils'
import { createAngularComponentDefinition, createComponentTypeDefinition } from './generate-angular-component'
import { generateAngularDirectivesFile } from './generate-angular-directives-file'
import generateValueAccessors from './generate-value-accessors'

export async function angularDirectiveProxyOutput(
  compilerCtx: CompilerCtx,
  outputTarget: OutputTargetAngular,
  components: ComponentCompilerMeta[],
  config: Config,
) {
  const filteredComponents = getFilteredComponents(outputTarget.excludeComponents, components)
  const rootDir = config.rootDir as string
  const pkgData = await readPackageJson(config, rootDir)

  const finalText = generateProxies(filteredComponents, pkgData, outputTarget, config.rootDir as string)

  await Promise.all([
    compilerCtx.fs.writeFile(outputTarget.directivesProxyFile, finalText),
    copyResources(config, outputTarget),
    generateAngularDirectivesFile(compilerCtx, filteredComponents, outputTarget),
    generateValueAccessors(compilerCtx, filteredComponents, outputTarget, config),
  ])
}

function getFilteredComponents(excludeComponents: string[] = [], cmps: ComponentCompilerMeta[]) {
  return sortBy(cmps, cmp => cmp.tagName).filter(c => !excludeComponents.includes(c.tagName) && !c.internal)
}

async function copyResources(config: Config, outputTarget: OutputTargetAngular) {
  if (!config.sys || !config.sys.copy || !config.sys.glob) {
    throw new Error('stencil is not properly initialized at this step. Notify the developer')
  }
  const srcDirectory = path.join(__dirname, '..', 'angular-component-lib')
  const destDirectory = path.join(path.dirname(outputTarget.directivesProxyFile), 'angular-component-lib')

  return config.sys.copy(
    [
      {
        src: srcDirectory,
        dest: destDirectory,
        keepDirStructure: false,
        warn: false,
      },
    ],
    srcDirectory,
  )
}

export function generateProxies(
  components: ComponentCompilerMeta[],
  pkgData: PackageJSON,
  outputTarget: OutputTargetAngular,
  rootDir: string,
) {
  const distTypesDir = path.dirname(pkgData.types)
  const dtsFilePath = path.join(rootDir, distTypesDir, GENERATED_DTS)
  const componentsTypeFile = relativeImport(outputTarget.directivesProxyFile, dtsFilePath, '.d.ts')

  /**
   * The collection of named imports from @angular/core.
   */
  const angularCoreImports = [
    'ChangeDetectionStrategy',
    'ChangeDetectorRef',
    'Component',
    'ElementRef',
    'EventEmitter',
    'NgZone',
  ]

  /**
   * The collection of named imports from the angular-component-lib/utils.
   */
  const componentLibImports = ['ProxyCmp', 'proxyOutputs']

  const imports = `/* tslint:disable */
/* auto-generated angular directive proxies */
${createImportStatement(angularCoreImports, '@angular/core')}

${createImportStatement(componentLibImports, './angular-component-lib/utils')}\n`
  /**
   * Generate JSX import type from correct location.
   * When using custom elements build, we need to import from
   * either the "components" directory or customElementsDir
   * otherwise we risk bundlers pulling in lazy loaded imports.
   */
  const generateTypeImports = () => {
    let importLocation = outputTarget.componentCorePackage
      ? normalizePath(outputTarget.componentCorePackage)
      : normalizePath(componentsTypeFile)
    importLocation += outputTarget.includeImportCustomElements
      ? `/${outputTarget.customElementsDir || 'components'}`
      : ''
    return `import ${
      outputTarget.includeImportCustomElements ? 'type ' : ''
    }{ ${IMPORT_TYPES} } from '${importLocation}';\n`
  }

  const typeImports = generateTypeImports()

  let sourceImports = ''

  /**
   * Build an array of Custom Elements build imports and namespace them
   * so that they do not conflict with the React wrapper names. For example,
   * IonButton would be imported as IonButtonCmp so as to not conflict with the
   * IonButton React Component that takes in the Web Component as a parameter.
   */
  if (outputTarget.includeImportCustomElements && outputTarget.componentCorePackage !== undefined) {
    const cmpImports = components.map(component => {
      const pascalImport = dashToPascalCase(component.tagName)

      return `import { defineCustomElement as define${pascalImport} } from '${normalizePath(
        outputTarget.componentCorePackage,
      )}/${outputTarget.customElementsDir || 'components'}/${component.tagName}.js';`
    })

    sourceImports = cmpImports.join('\n')
  }

  const proxyFileOutput = []

  const filterInternalProps = (prop: { name: string; internal: boolean }) => !prop.internal
  const mapPropName = (prop: { name: string }) => prop.name

  const { includeImportCustomElements, componentCorePackage, customElementsDir } = outputTarget

  for (const cmpMeta of components) {
    const tagNameAsPascal = dashToPascalCase(cmpMeta.tagName)

    const inputs: string[] = []

    if (cmpMeta.properties) {
      inputs.push(...cmpMeta.properties.filter(filterInternalProps).map(mapPropName))
    }

    if (cmpMeta.virtualProperties) {
      inputs.push(...cmpMeta.virtualProperties.map(mapPropName))
    }

    inputs.sort()

    const outputs: string[] = []

    if (cmpMeta.events) {
      outputs.push(...cmpMeta.events.filter(filterInternalProps).map(mapPropName))
    }

    const methods: string[] = []

    if (cmpMeta.methods) {
      methods.push(...cmpMeta.methods.filter(filterInternalProps).map(mapPropName))
    }

    /**
     * For each component, we need to generate:
     * 1. The @Component decorated class
     * 2. The component interface (using declaration merging for types).
     */
    const componentDefinition = createAngularComponentDefinition(
      cmpMeta.tagName,
      inputs,
      outputs,
      methods,
      includeImportCustomElements,
    )
    const componentTypeDefinition = createComponentTypeDefinition(
      tagNameAsPascal,
      cmpMeta.events,
      componentCorePackage,
      includeImportCustomElements,
      customElementsDir,
    )

    proxyFileOutput.push(componentDefinition, '\n')
    proxyFileOutput.push(componentTypeDefinition, '\n')
  }

  const final: string[] = [imports, typeImports, sourceImports, ...proxyFileOutput]

  return final.join('\n') + '\n'
}

const GENERATED_DTS = 'components.d.ts'
const IMPORT_TYPES = 'Components'

// libs/output-target-angular/src/lib/output-angular.ts
import { join, dirname } from 'path'
import type { CompilerCtx, ComponentCompilerMeta, Config } from '@stencil/core/internal'
import type { OutputTargetAngular, PackageJSON } from './types'
import { relativeImport, normalizePath, sortBy, readPackageJson, dashToPascalCase } from './utils'
import { createComponentDefinition } from './generate-angular-component'
import { generateAngularDirectivesFile } from './generate-angular-directives-file'
import generateValueAccessors from './generate-value-accessors'

export async function angularDirectiveProxyOutput(
  compilerCtx: CompilerCtx,
  outputTarget: OutputTargetAngular,
  components: ComponentCompilerMeta[],
  config: Config,
) {
  const filteredComponents = getFilteredComponents(outputTarget.excludeComponents, components)
  const rootDir = config.rootDir as string
  const pkgData = await readPackageJson(rootDir)

  const finalText = generateProxies(filteredComponents, pkgData, outputTarget, config.rootDir as string)

  let finalExcludedMeta = ''
  if (outputTarget.outputType === 'standalone') {
    const excludedComponents = getExcludedComponents(outputTarget.excludeComponents, components)
    finalExcludedMeta = generateMeta(excludedComponents, pkgData, outputTarget, config.rootDir as string)
  }

  await Promise.all([
    compilerCtx.fs.writeFile(outputTarget.directivesProxyFile, finalText),
    copyResources(config, outputTarget),
    outputTarget.outputType === 'standalone'
      ? compilerCtx.fs.writeFile(outputTarget.directivesMetaFile, finalExcludedMeta)
      : generateAngularDirectivesFile(compilerCtx, filteredComponents, outputTarget),
    generateValueAccessors(compilerCtx, filteredComponents, outputTarget, config),
  ])
}

function getFilteredComponents(excludeComponents: string[] = [], cmps: ComponentCompilerMeta[]) {
  return sortBy(cmps, cmp => cmp.tagName).filter(c => !excludeComponents.includes(c.tagName) && !c.internal)
}

function getExcludedComponents(excludeComponents: string[] = [], cmps: ComponentCompilerMeta[]) {
  return sortBy(cmps, cmp => cmp.tagName).filter(c => excludeComponents.includes(c.tagName) && !c.internal)
}

async function copyResources(config: Config, outputTarget: OutputTargetAngular) {
  if (!config.sys || !config.sys.copy || !config.sys.glob) {
    throw new Error('stencil is not properly initialized at this step. Notify the developer')
  }
  const srcDirectory = join(__dirname, '../../../angular-component-lib/utils.ts')
  const destDirectory = join(dirname(outputTarget.directivesProxyFile), 'angular-component-lib/utils.ts')

  return config.sys.copy(
    [
      {
        src: srcDirectory,
        dest: destDirectory,
        keepDirStructure: false,
        warn: false,
        ignore: [],
      },
    ],
    srcDirectory,
  )
}

export function generateProxies(
  components: ComponentCompilerMeta[],
  pkgData: PackageJSON,
  outputTarget: OutputTargetAngular,
  rootDir: string,
) {
  const distTypesDir = dirname(pkgData.types)
  const dtsFilePath = join(rootDir, distTypesDir, GENERATED_DTS)
  const componentsTypeFile = relativeImport(outputTarget.directivesProxyFile, dtsFilePath, '.d.ts')

  let imports = []
  imports.push(`/* tslint:disable */`)
  imports.push(`/* auto-generated angular directive proxies */`)
  imports.push(
    `import { ChangeDetectionStrategy, ChangeDetectorRef, Component, ElementRef, NgZone, EventEmitter, NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';`,
  )
  imports.push(`import { ProxyCmp, proxyOutputs } from './angular-component-lib/utils';`)

  if (outputTarget.outputType === 'standalone' || outputTarget.outputType === 'module') {
    imports = [
      ...imports,
      ...components.map(component => {
        const tagNameAsPascal = dashToPascalCase(component.tagName)
        return `import { defineCustomElement as define${tagNameAsPascal} } from '${normalizePath(
          !outputTarget.componentCorePackage ? componentsTypeFile : outputTarget.componentCorePackage,
        )}/components/${component.tagName}';`
      }),
    ]
  }

  imports.push(``)

  const typeImports = !outputTarget.componentCorePackage
    ? `import type { ${IMPORT_TYPES} } from '${normalizePath(componentsTypeFile)}';`
    : `import type { ${IMPORT_TYPES} } from '${normalizePath(outputTarget.componentCorePackage)}/components';`

  const final: string[] = [
    imports.join('\n'),
    typeImports,
    components
      .map(
        createComponentDefinition(outputTarget.componentCorePackage!, distTypesDir, rootDir, outputTarget.outputType),
      )
      .join('\n'),
  ]

  return final.join('\n') + '\n'
}

function generateMeta(
  components: ComponentCompilerMeta[],
  _pkgData: PackageJSON,
  _outputTarget: OutputTargetAngular,
  _rootDir: string,
) {
  const imports = []
  imports.push(`/* tslint:disable */`)
  imports.push(`/* auto-generated angular directive proxies */`)

  function createComponentMeta(cmpMeta: ComponentCompilerMeta) {
    const tagNameAsPascal = dashToPascalCase(cmpMeta.tagName)

    // Collect component meta
    const inputs = [
      ...cmpMeta.properties.filter(prop => !prop.internal).map(prop => prop.name),
      ...cmpMeta.virtualProperties.map(prop => prop.name),
    ].sort()
    const outputs = cmpMeta.events.filter(ev => !ev.internal).map(prop => prop)
    const methods = cmpMeta.methods.filter(method => !method.internal).map(prop => prop.name)

    const lines = []
    lines.push(`export const ${tagNameAsPascal}Inputs = ['${inputs.join(`', '`)}']`)
    lines.push(`export const ${tagNameAsPascal}Outputs = ['${outputs.map(output => output.name).join(`', '`)}']`)
    lines.push(`export const ${tagNameAsPascal}Methods = ['${methods.join(`', '`)}']`)
    return lines.join('\n')
  }

  const final: string[] = [imports.join('\n'), components.map(cmp => createComponentMeta(cmp)).join('\n')]

  return final.join('\n') + '\n'
}

const GENERATED_DTS = 'components.d.ts'
const IMPORT_TYPES = 'Components, FileUploadRejectedFile'
