// packages/output-targets/angular/angular-component-lib/utils.ts
/* eslint-disable */
/* tslint:disable */
import { fromEvent } from 'rxjs'

export const proxyInputs = (Cmp: any, inputs: string[]) => {
  const Prototype = Cmp.prototype
  inputs.forEach(item => {
    Object.defineProperty(Prototype, item, {
      get() {
        return this.el[item]
      },
      set(val: any) {
        this.z.runOutsideAngular(() => (this.el[item] = val))
      },
    })
  })
}

export const proxyMethods = (Cmp: any, methods: string[]) => {
  const Prototype = Cmp.prototype
  methods.forEach(methodName => {
    Prototype[methodName] = function () {
      const args = arguments
      return this.z.runOutsideAngular(() => this.el[methodName].apply(this.el, args))
    }
  })
}

export const proxyOutputs = (instance: any, el: any, events: string[]) => {
  events.forEach(eventName => (instance[eventName] = fromEvent(el, eventName)))
}

export const defineCustomElement = (tagName: string, customElement: any) => {
  if (customElement !== undefined && typeof customElements !== 'undefined' && !customElements.get(tagName)) {
    customElements.define(tagName, customElement)
  }
}

// tslint:disable-next-line: only-arrow-functions
export function ProxyCmp(opts: { defineCustomElementFn?: () => void; inputs?: any; methods?: any }) {
  const decorator = function (cls: any) {
    const { defineCustomElementFn, inputs, methods } = opts

    if (defineCustomElementFn !== undefined) {
      defineCustomElementFn()
    }

    if (inputs) {
      proxyInputs(cls, inputs)
    }
    if (methods) {
      proxyMethods(cls, methods)
    }
    return cls
  }
  return decorator
}

// examples/angular/src/app/lib/directives/angular-component-lib/utils.ts
// import { fromEvent } from 'rxjs';
// import { map } from 'rxjs/operators';
import { EventEmitter } from '@angular/core'

export const proxyInputs = (Cmp: any, inputs: string[]) => {
  const Prototype = Cmp.prototype
  inputs.forEach(item => {
    Object.defineProperty(Prototype, item, {
      get() {
        return this.el[item]
      },
      set(val: any) {
        this.z.runOutsideAngular(() => (this.el[item] = val))
      },
    })
  })
}

export const proxyMethods = (Cmp: any, methods: string[]) => {
  const Prototype = Cmp.prototype
  methods.forEach(methodName => {
    Prototype[methodName] = function () {
      const args = arguments
      return this.z.runOutsideAngular(() => this.el[methodName].apply(this.el, args))
    }
  })
}

export const proxyOutputs = (instance: any, el: any, events: string[]) => {
  events.forEach(eventName => (instance[eventName] = new EventEmitter()))

  events.forEach(eventName => {
    el.addEventListener(eventName, (event: any) => {
      console.log(eventName, event)
      let emittedValue = event
      if ('detail' in event) {
        emittedValue = event.detail
      }
      instance[eventName].emit(emittedValue)
    })
  })
}

// tslint:disable-next-line: only-arrow-functions
export function ProxyCmp(opts: { inputs?: any; methods?: any }) {
  const decorator = function (cls: any) {
    if (opts.inputs) {
      proxyInputs(cls, opts.inputs)
    }
    if (opts.methods) {
      proxyMethods(cls, opts.methods)
    }
    return cls
  }
  return decorator
}
